---
apiVersion: v2
name: mlflow
description: MLflow Tracking Server
type: application
version: 3.7.0
appVersion: 3.7.0
home: https://github.com/ministryofjustice/analytical-platform-mlflow
sources:
  - https://github.com/mlflow/mlflow
maintainers:
  - name: jacobwoffenden
    email: jacob.woffenden@digital.justice.gov.uk
    url: github.com/jacobwoffenden
